### ISSUE TITLE
Remove support for old style pack configs

### ISSUE THREAD

**Issue by Kami** [StackStorm/st2#3424]
They have been deprecated for quite a long time now and they are just causing confusion and pain since they are not user friendly.

## TODO

- [x] Code changes - https://github.com/StackStorm/st2/pull/3434
- [x] Update code to throw a friendly error message if `<pack root>/config.yaml` file is found which tells user old-style configs are not supported anymore and links to the appropriate documentation page - https://github.com/StackStorm/st2/pull/3434
- [x] Upgrade notes and various "notice" entries in the docs
- [x] Complete reviews for PRs to clean up Exchange

**Comment by Kami** [comment]
@LindsayHill You can help me with the last task if you get a chance :)

**Comment by LindsayHill** [comment]
Yeah, I guess I will. I did a lot of them last year, but there's a couple left. 

Wonder if we should add tests that reject all new PRs that include `config.yaml`?

**Comment by Kami** [comment]
Yeah, adding a lint / build check would be good.

**Comment by LindsayHill** [comment]
Looks like this is our list to work through:

- [ ] github.com/StackStorm-Exchange/stackstorm-aws/tree/master/config.yaml     
- [ ] github.com/StackStorm-Exchange/stackstorm-libcloud/tree/master/config.yaml   
- [ ] github.com/StackStorm-Exchange/stackstorm-rabbitmq/tree/master/config.yaml
- [ ] github.com/StackStorm-Exchange/stackstorm-azure/tree/master/config.yaml   
- [ ] github.com/StackStorm-Exchange/stackstorm-mssql/tree/master/config.yaml      
- [ ] github.com/StackStorm-Exchange/stackstorm-trello/tree/master/config.yaml
- [ ] github.com/StackStorm-Exchange/stackstorm-docker/tree/master/config.yaml  
- [ ] github.com/StackStorm-Exchange/stackstorm-mysql/tree/master/config.yaml      
- [ ] github.com/StackStorm-Exchange/stackstorm-typeform/tree/master/config.yaml
- [ ] github.com/StackStorm-Exchange/stackstorm-email/tree/master/config.yaml   
- [ ] github.com/StackStorm-Exchange/stackstorm-openstack/tree/master/config.yaml  
- [ ] github.com/StackStorm-Exchange/stackstorm-vsphere/tree/master/config.yaml
- [ ] github.com/StackStorm-Exchange/stackstorm-git/tree/master/config.yaml     
- [ ] github.com/StackStorm-Exchange/stackstorm-packer/tree/master/config.yaml     
- [ ] github.com/StackStorm-Exchange/stackstorm-witai/tree/master/config.yaml

**Comment by LindsayHill** [comment]
Docs PR: https://github.com/StackStorm/st2docs/pull/507

Not sure if I've got all the references, but must be close

**Comment by LindsayHill** [comment]
Closed since #3434 is now merged
