### ISSUE TITLE
Pack Install shouldn't set '755' permissions on all pack content

### ISSUE THREAD

**Issue by armab** [StackStorm/st2#3660]
History leads to `2015` and https://github.com/StackStorm/st2/pull/2009 https://github.com/StackStorm/st2/pull/2012 changes.

I don't think it's good that during a pack install we additionally set `755` permissions (`+x`) on all files in a pack, including yaml files and everything else. Additionally, `+x` on "others" is even more nasty.

Instead we should try to rely on permissions set from `git`, eg. preserve the original permissions from the pack + change ownership so stackstorm-related services can work OK.

#### TODO
- [ ] Revert the change
- [ ] Research corner cases
- [ ] Test
  - [ ] Make sure `git` preserves the original pack permissions
  - [ ] Check WebUI
  - [ ] Check st2flow (including `save` & `run`)
    - [ ] EL6
    - [ ] EL7
    - [ ] Ubuntu14
    - [ ] Ubuntu16
- [ ] Compatibility: find all executable files in StackStorm/exchange packs and explicitly set `+x` (if not set)
- [ ] Hide the pack content (dir) for "other" users, allow only for owners + stackstorm groups (?)

A note from @enykeev 
> we need both st2api and actionrunner to be able to read and write them. At the same time, we don’t want to run st2api with sudo privileges as it would create additional risk

----
Initial effort would be to check if this can even work and won't break everything.

**Comment by nmaludy** [comment]
+1 want to stay up to date on the decision here so i can keep puppet-st2 in sync

**Comment by armab** [comment]
cc @lakshmi-kannan maybe you remember any context from 2015 and any possible corner cases.

**Comment by LindsayHill** [comment]
Initial thoughts are that 755 feels wrong. The user/group should be set, but then it should probably either use git permissions, or 644 for files & 755 for directories. Can't think of any reason why files need to be executable.

**Comment by armab** [comment]
From what I understand, long time ago `git` didn't preserve the correct file permissions (?) during the `git clone` and so `.sh` scripts coming with the packs (shell-runner) were deployed without the needed `+x` flag.
