### ISSUE TITLE
Remove deprecated "timer" section in st2.conf

### ISSUE THREAD

**Issue by Kami** [StackStorm/st2#4425]
In v2.9.0 we deprecated ``timer`` section in ``st2.conf`` in favor of new ``timersengine`` section.

We need to remove old and deprecated ``timer`` section in ``st2.conf``.

The current approach is also confusing - timer section has been deprecated and timerengine is the preferred approach yet the how code is structured, "timer" section actually has precedence because of the way how our code is structured.

## TODO

- [ ] Remove from config.py
- [ ] Update affected code
- [ ] Update upgrade notes
