### ISSUE TITLE
EL7/U16 -> Mongo 4.0 Master Issue

### ISSUE THREAD

**Issue by punkrokk** [StackStorm/st2#4972]
Since Mongo 3.4 has been deprecated, we need to following Issues resolved in order to update/support Mongo ~3.6~ 4.0 in ST2 v3.3.0

- [x] stackstorm/st2-packages#643 one line installer scripts
- [x] StackStorm/ansible-st2#264 ansible
- [x] StackStorm/puppet-st2#298 puppet
- [x] StackStorm/st2docs#988 st2docs
- [x] st2docs https://github.com/StackStorm/st2docs/blob/master/docs/source/install/__mongodb_note.rst https://github.com/StackStorm/st2docs/pull/994
- [x] update TravisCI and CircleCI to use mongodb `4.0` instead of `3.4`

**Comment by armab** [comment]
RE st2docs, the following documentation page will need an update too:
https://github.com/StackStorm/st2docs/blob/master/docs/source/install/__mongodb_note.rst

**Comment by amanda11** [comment]
@punkrokk I think I may have covered the st2docs change under this one: https://github.com/StackStorm/st2docs/pull/994/files (was amending a few other files when removing EL6 for functionality I knew we'd changed!)

**Comment by amanda11** [comment]
@punkrokk In the st2 repo. In the circleci config file. When it runs the integration tests it points to the docker mongo:3.4. Does that need to be altered to point to mongo 4.0 as part of this issue?

**Comment by armab** [comment]
For future reference, ideally not to mix several logically independent changes in one PR like EL6 deprecation _and_ MongoDB 4.0 _and_ EL8 link update _and_ something else.
It's always better to create several dedicated PRs for each change for easy review and change/history reasons.

**Comment by punkrokk** [comment]
@armab Good call, I think I lost focus on what the actual issue was !!!

**Comment by amanda11** [comment]
> For future reference, ideally not to mix several logically independent changes in one PR like EL6 deprecation _and_ MongoDB 4.0 _and_ EL8 link update _and_ something else.
> It's always better to create several dedicated PRs for each change for easy review and change/history reasons.

Point noted. Got carried away when noticing errors in docs. Will do separate PRs next time to make it easier to review/track.

**Comment by amanda11** [comment]
@punkrokk I noticed that in st2 repo the travis and circleci still refer to mongo 3.4 for their runs on python 2.7, not mongo 4.0. Do we need another checkbox to resolve those?

**Comment by punkrokk** [comment]
I think so. @armab?

JP Bourget / @punkrokk

**Comment by armab** [comment]
Sure, good spotting!

**Comment by amanda11** [comment]
@armab @punkrokk I checked in a PR that changed the ST2 CirlceCI and Travis to use mongo 4.0, is there any other CI/CD places that need changing (it was the one that I had noticed was missing)? Or is that mongo 4.0 finished now?

**Comment by armab** [comment]
@amanda11 Thanks for tracking this down! Sure, feel free to close the issue.
