### ISSUE TITLE
MongoDB 4.4 support tracking issue

### ISSUE THREAD

**Issue by Kami** [StackStorm/st2#5249]
## TODO

- [x] Update dependencies and code to support MongoDB 4.4 (in addition to 3.6 and 4.0) - #5177, #5215
- [x] Run unit + integration tests tests against MongoDB 4.4 on CI - #5177
- [x] Fix projection queries compatibility - #5247
- [x] Run end to end tests with  MongoDB 4.4 on Ubuntu 20.04 (depends on Ubuntu 20.04 change)

Related discussion - https://github.com/StackStorm/discussions/issues/68 (which includes things outside StackStorm/st2).

**Comment by Kami** [comment]
@nzlosh ^ Just FYI.

I will look into a fix for projection issue when I get a chance. I think it should be pretty straight forward.

**Comment by Kami** [comment]
Closing.
